name: Security Check - Terraform

on: [pull_request, push]

jobs:
  checkov:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      # security-events: write

    steps:
      - name: Setup GitHub Actions
        uses: actions/checkout@master

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./infra
          framework: terraform
          soft_fail: true
          download_external_modules: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
